apiVersion: v1
kind: Service
metadata:
  name: pgbouncer-svc
  namespace: db
spec:
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
    targetPort: 5432
  - name: pgbouncer
    port: 6432
    protocol: TCP
    targetPort: 6432
  selector:
    app: pgbouncer
  type: ClusterIP