apiVersion: v1
kind: ConfigMap
metadata:
  name: conf
  namespace: db
data:
  pgbouncer.ini: |
    [databases]
    postgres=host=postgresql-svc.db port=5432 dbname=postgres
    testdb=host=postgresql-svc.db port=5432 user=test_user password=test dbname=testdb
    certdb=host=postgresql-svc.db port=5432 dbname=certdb

    [pgbouncer]
    listen_port=6432
    listen_addr=0.0.0.0
    auth_file=/opt/bitnami/pgbouncer/conf/userlist.txt
    auth_type=trust
    pidfile=/opt/bitnami/pgbouncer/tmp/pgbouncer.pid
    logfile=/opt/bitnami/pgbouncer/logs/pgbouncer.log
    admin_users=postgres
    client_tls_sslmode=disable
    server_tls_sslmode=disable
    pool_mode=session
    max_client_conn=1000
    server_reset_query=DISCARD ALL
    ignore_startup_parameters=extra_float_digits