apiVersion: v1
kind: Service
metadata:
  name: postgresql-svc
  labels:
    app: db
  # annotations:
  #   cloud.google.com/load-balancer-type: "Internal"
  namespace: db
spec:
  type: ClusterIP
  ports:
    - name: tcp-postgresql
      port: 5432
      targetPort: tcp-postgresql
  selector:
    app: db
